import type { Product, Category } from './types';

export const categories: Category[] = [
  {
    id: 'cat-1',
    name: 'Sarees',
    slug: 'sarees',
    description: 'Handwoven drapes of timeless grace — from Banarasi silk to chiffon.',
    image:
      'https://images.pexels.com/photos/2723623/pexels-photo-2723623.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    product_count: 48,
  },
  {
    id: 'cat-2',
    name: 'Lehengas',
    slug: 'lehengas',
    description: 'Opulent skirts adorned with zardozi, mirror work, and resham embroidery.',
    image:
      'https://images.pexels.com/photos/25811178/pexels-photo-25811178.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    product_count: 32,
  },
  {
    id: 'cat-3',
    name: 'Anarkalis',
    slug: 'anarkalis',
    description: 'Floor-length silhouettes that flow with regal fluidity.',
    image:
      'https://images.pexels.com/photos/30703860/pexels-photo-30703860.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    product_count: 26,
  },
  {
    id: 'cat-4',
    name: 'Bridal Couture',
    slug: 'bridal-couture',
    description: 'Heirloom pieces crafted for the once-in-a-lifetime celebration.',
    image:
      'https://images.pexels.com/photos/14840508/pexels-photo-14840508.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    product_count: 18,
  },
  {
    id: 'cat-5',
    name: 'Kurtis & Suits',
    slug: 'kurtis-suits',
    description: 'Everyday elegance with traditional craftsmanship.',
    image:
      'https://images.pexels.com/photos/7176438/pexels-photo-7176438.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    product_count: 54,
  },
  {
    id: 'cat-6',
    name: 'Dupattas & Stoles',
    slug: 'dupattas-stoles',
    description: 'The finishing flourish — Phulkari, Banarasi, and hand-painted.',
    image:
      'https://images.pexels.com/photos/8886963/pexels-photo-8886963.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    product_count: 21,
  },
];

export const products: Product[] = [
  {
    id: 'prod-001',
    name: 'Rani Burgundy Banarasi Silk Saree',
    slug: 'rani-burgundy-banarasi-silk-saree',
    description:
      "A regal Banarasi silk saree in deep burgundy, woven with gold zari motifs. Each thread tells a story of Varanasi's master weavers.",
    price: 28900,
    compare_at_price: 36000,
    category: 'Sarees',
    collection: 'Bridal',
    fabric: 'Silk',
    color: 'Burgundy',
    size: ['Free Size'],
    images: [
      'https://images.pexels.com/photos/2723623/pexels-photo-2723623.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/36951188/pexels-photo-36951188.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    featured: true,
    in_stock: true,
    rating: 4.9,
    review_count: 127,
    tags: ['Bestseller', 'Handwoven'],
    created_at: '2026-08-15T10:00:00Z',
  },
  {
    id: 'prod-002',
    name: 'Sindoor Red Bridal Lehenga',
    slug: 'sindoor-red-bridal-lehenga',
    description:
      'A breathtaking bridal lehenga in sindoor red, featuring intricate gold zardozi embroidery and a hand-embellished dupatta.',
    price: 125000,
    compare_at_price: 158000,
    category: 'Bridal Couture',
    collection: 'Bridal',
    fabric: 'Velvet',
    color: 'Red',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    images: [
      'https://images.pexels.com/photos/25811178/pexels-photo-25811178.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/8596205/pexels-photo-8596205.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    featured: true,
    in_stock: true,
    rating: 5.0,
    review_count: 89,
    tags: ['Bridal Exclusive', 'Custom Fit'],
    created_at: '2026-08-20T10:00:00Z',
  },
  {
    id: 'prod-003',
    name: 'Gulabo Teal Chiffon Saree',
    slug: 'gulabo-teal-chiffon-saree',
    description:
      'A flowing teal chiffon saree with delicate resham floral embroidery along the pallu. Effortless grace for festive gatherings.',
    price: 14500,
    compare_at_price: null,
    category: 'Sarees',
    collection: 'Festive',
    fabric: 'Chiffon',
    color: 'Teal',
    size: ['Free Size'],
    images: [
      'https://images.pexels.com/photos/7176438/pexels-photo-7176438.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/2723623/pexels-photo-2723623.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    featured: true,
    in_stock: true,
    rating: 4.7,
    review_count: 64,
    tags: ['New Arrival'],
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'prod-004',
    name: 'Marigold Pink Lehenga with Mirror Work',
    slug: 'marigold-pink-lehenga-mirror-work',
    description:
      'A vibrant pink lehenga adorned with hand-stitched mirror work and gota patti detailing. A celebration in every fold.',
    price: 67000,
    compare_at_price: 82000,
    category: 'Lehengas',
    collection: 'Festive',
    fabric: 'Georgette',
    color: 'Pink',
    size: ['XS', 'S', 'M', 'L'],
    images: [
      'https://images.pexels.com/photos/12411113/pexels-photo-12411113.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/13039870/pexels-photo-13039870.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    featured: true,
    in_stock: true,
    rating: 4.8,
    review_count: 52,
    tags: ['Festive Special'],
    created_at: '2026-08-25T10:00:00Z',
  },
  {
    id: 'prod-005',
    name: 'Sahiba Maroon Anarkali Suit',
    slug: 'sahiba-maroon-anarkali-suit',
    description:
      'A floor-length maroon anarkali in premium velvet with gold sequin detailing. Regal silhouette for evening occasions.',
    price: 38500,
    compare_at_price: 45000,
    category: 'Anarkalis',
    collection: 'Heritage',
    fabric: 'Velvet',
    color: 'Maroon',
    size: ['S', 'M', 'L', 'XL'],
    images: [
      'https://images.pexels.com/photos/2531734/pexels-photo-2531734.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/30703860/pexels-photo-30703860.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    featured: true,
    in_stock: true,
    rating: 4.6,
    review_count: 38,
    tags: ['Heritage'],
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'prod-006',
    name: 'Gauri Ivory Organza Saree',
    slug: 'gauri-ivory-organza-saree',
    description:
      'A luminous ivory organza saree with hand-painted floral motifs and a scalloped gold border. Contemporary heritage.',
    price: 22000,
    compare_at_price: null,
    category: 'Sarees',
    collection: 'Contemporary',
    fabric: 'Organza',
    color: 'Ivory',
    size: ['Free Size'],
    images: [
      'https://images.pexels.com/photos/19567863/pexels-photo-19567863.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/30703860/pexels-photo-30703860.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    featured: true,
    in_stock: true,
    rating: 4.8,
    review_count: 73,
    tags: ['New Arrival', 'Bestseller'],
    created_at: '2026-09-05T10:00:00Z',
  },
  {
    id: 'prod-007',
    name: 'Padmini Red Bridal Couture Gown',
    slug: 'padmini-red-bridal-couture-gown',
    description:
      'A masterpiece of bridal couture — deep red velvet with hand-embroidered gold zardozi, sequins, and pearl detailing.',
    price: 185000,
    compare_at_price: null,
    category: 'Bridal Couture',
    collection: 'Bridal',
    fabric: 'Velvet',
    color: 'Red',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    images: [
      'https://images.pexels.com/photos/14840508/pexels-photo-14840508.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/11746622/pexels-photo-11746622.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    featured: true,
    in_stock: true,
    rating: 5.0,
    review_count: 41,
    tags: ['Bridal Exclusive', 'Made to Order'],
    created_at: '2026-08-18T10:00:00Z',
  },
  {
    id: 'prod-008',
    name: 'Chandni Gold Brocade Lehenga',
    slug: 'chandni-gold-brocade-lehenga',
    description:
      'A golden brocade lehenga with traditional buti motifs and a contrast burgundy border. Festive opulence redefined.',
    price: 89000,
    compare_at_price: 110000,
    category: 'Lehengas',
    collection: 'Heritage',
    fabric: 'Brocade',
    color: 'Gold',
    size: ['S', 'M', 'L', 'XL'],
    images: [
      'https://images.pexels.com/photos/13204677/pexels-photo-13204677.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/13124449/pexels-photo-13124449.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    featured: false,
    in_stock: true,
    rating: 4.7,
    review_count: 29,
    tags: ['Heritage'],
    created_at: '2026-07-28T10:00:00Z',
  },
  {
    id: 'prod-009',
    name: 'Meher Cotton Kurti with Chikankari',
    slug: 'meher-cotton-kurti-chikankari',
    description:
      'A breathable cotton kurti with authentic Lucknowi chikankari hand embroidery. Everyday elegance, elevated.',
    price: 4800,
    compare_at_price: 6500,
    category: 'Kurtis & Suits',
    collection: 'Contemporary',
    fabric: 'Cotton',
    color: 'White',
    size: ['XS', 'S', 'M', 'L', 'XL'],
    images: [
      'https://images.pexels.com/photos/30703860/pexels-photo-30703860.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/19567863/pexels-photo-19567863.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    featured: false,
    in_stock: true,
    rating: 4.5,
    review_count: 156,
    tags: ['Bestseller', 'Hand Embroidered'],
    created_at: '2026-09-03T10:00:00Z',
  },
  {
    id: 'prod-010',
    name: 'Roohi Maroon Net Dupatta',
    slug: 'roohi-maroon-net-dupatta',
    description:
      'A sheer net dupatta in deep maroon with scattered sequin work and a heavily embroidered border.',
    price: 6500,
    compare_at_price: null,
    category: 'Dupattas & Stoles',
    collection: 'Festive',
    fabric: 'Net',
    color: 'Maroon',
    size: ['Free Size'],
    images: [
      'https://images.pexels.com/photos/8886963/pexels-photo-8886963.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/8886965/pexels-photo-8886965.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    featured: false,
    in_stock: true,
    rating: 4.4,
    review_count: 22,
    tags: ['New Arrival'],
    created_at: '2026-09-07T10:00:00Z',
  },
  {
    id: 'prod-011',
    name: 'Amrita Georgette Anarkali in Emerald',
    slug: 'amrita-georgette-anarkali-emerald',
    description:
      'An emerald green georgette anarkali with silver zari floral embroidery. A versatile piece for celebrations.',
    price: 32000,
    compare_at_price: 40000,
    category: 'Anarkalis',
    collection: 'Festive',
    fabric: 'Georgette',
    color: 'Green',
    size: ['S', 'M', 'L', 'XL'],
    images: [
      'https://images.pexels.com/photos/28405815/pexels-photo-28405815.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/7176438/pexels-photo-7176438.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    featured: false,
    in_stock: true,
    rating: 4.6,
    review_count: 34,
    tags: ['Festive Special'],
    created_at: '2026-08-22T10:00:00Z',
  },
  {
    id: 'prod-012',
    name: 'Nargis Spring Chiffon Saree',
    slug: 'nargis-spring-chiffon-saree',
    description:
      'A breezy spring chiffon saree in blush pink with silver thread work along the pallu. Light, luminous, effortless.',
    price: 12500,
    compare_at_price: 16000,
    category: 'Sarees',
    collection: 'Spring-Summer',
    fabric: 'Chiffon',
    color: 'Pink',
    size: ['Free Size'],
    images: [
      'https://images.pexels.com/photos/32982848/pexels-photo-32982848.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/32982934/pexels-photo-32982934.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    featured: false,
    in_stock: false,
    rating: 4.5,
    review_count: 47,
    tags: ['Spring-Summer'],
    created_at: '2026-09-08T10:00:00Z',
  },
];

export function formatPrice(price: number): string {
  return `₹${price.toLocaleString('en-IN')}`;
}
